#389. Find the Difference
''' You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters. '''

#Note: In the constraints, they mentioned t.length == s.length + 1 so t string len > s string len

def findTheDifference(s,t):
    sum_s = sum(ord(i) for i in s)
    sum_t = sum(ord(i) for i in t)
    diff = chr(sum_t - sum_s)
    return diff
s = input("Enter first string: ")
t = input("Enter second string: ")
result = findTheDifference(s,t)
print(f"added letter is: {result}")

'''
output:
Enter first string: hello
Enter second string: ollehy
added letter is: y

'''